const carInfo = [
    {
        id: 1,
        logo: "https://3.bp.blogspot.com/-yJJevR3Ak_o/UL5_PX8D32I/AAAAAAAAHEE/87JPHXfJCiQ/s1600/Maruti+Suzuki+Logo.png",
        name: "marui suzuki",
        color: "Black",
        yearofManufacure: "2014",
        validDate: "2040",
        kms: "9832RLD",
        location: "India",
        owners: "1nd owners",
        fiments: "478343",
        transmission: "Automaic",
    },
    {
        id: 2,
        logo: "https://www.carlogos.org/logo/Hyundai-symbol-blue-2560x1440.png",
        name: "Hyundai",
        color: "Black",
        yearofManufacure: "2014",
        validDate: "2040",
        kms: "9832RLD",
        location: "India",
        owners: "2nd owners",
        fiments: "478343",
        transmission: "Automaic",
    },
    {
        id: 3,
        logo: "https://www.carlogos.org/logo/Renault-logo-2015-2048x2048.png",
        name: "Renault",
        color: "Black",
        yearofManufacure: "2014",
        validDate: "2040",
        kms: "9832RLD",
        location: "India",
        owners: "1nd owners",
        fiments: "478343",
        transmission: "Automaic",
    },
    {
        id: 4,
        logo: "https://www.pixelstalk.net/wp-content/uploads/2016/05/Honda-Logo-High-Definition-Backgrounds.png",
        name: "Honda",
        color: "Black",
        yearofManufacure: "2014",
        validDate: "2040",
        kms: "9832RLD",
        location: "India",
        owners: "3nd owners",
        fiments: "478343",
        transmission: "Manual",
    },
    {
        id: 5,
        logo: "https://www.carlogos.org/logo/Tata-Group-logo-3840x2160.png",
        name: "TATA",
        color: "Black",
        yearofManufacure: "2014",
        validDate: "2040",
        kms: "9832RLD",
        location: "India",
        owners: "2nd owners",
        fiments: "478343",
        transmission: "Automaic",
    },
    {
        id: 6,
        logo: "https://www.pinclipart.com/picdir/big/379-3793662_ford-logo-png-transparent-ford-f-150-logo.png",
        name: "Ford",
        color: "Black",
        yearofManufacure: "2014",
        validDate: "2040",
        kms: "9832RLD",
        location: "India",
        owners: "1nd owners",
        fiments: "478343",
        transmission: "Manual",
    },
    {
        id: 7,
        logo: "https://www.carlogos.org/logo/Volkswagen-logo-2019-1500x1500.png",
        name: "volkswagen",
        color: "Black",
        yearofManufacure: "2014",
        validDate: "2040",
        kms: "9832RLD",
        location: "India",
        owners: "3nd owners",
        fiments: "478343",
        transmission: "Automaic",
    },
    {
        id: 8,
        logo: "https://www.carlogos.org/logo/Mahindra-logo-2560x1440.png",
        name: "mahindra",
        color: "Black",
        yearofManufacure: "2014",
        validDate: "2040",
        kms: "9832RLD",
        location: "India",
        owners: "1nd owners",
        fiments: "478343",
        transmission: "Manual",
    },
    {
        id: 10,
        logo: "https://logodix.com/logo/521.png",
        name: "Toyota",
        color: "Black",
        yearofManufacure: "2014",
        validDate: "2040",
        kms: "9832RLD",
        location: "India",
        owners: "1nd owners",
        fiments: "478343",
        transmission: "manual",
    },
    {
        id: 11,
        logo: "https://logos-download.com/wp-content/uploads/2016/02/BMW_logo_big_transparent_png.png",
        name: "BMW",
        color: "Black",
        yearofManufacure: "2014",
        validDate: "2040",
        kms: "9832RLD",
        location: "India",
        owners: "3nd owners",
        fiments: "478343",
        transmission: "Automaic",
    },
    {
        id: 12,
        logo: "https://logos-world.net/wp-content/uploads/2020/05/Mercedes-Benz-Logo.png",
        name: "Mercedes Benz",
        color: "Black",
        yearofManufacure: "2014",
        validDate: "2040",
        kms: "9832RLD",
        location: "India",
        owners: "1nd owners",
        fiments: "478343",
        transmission: "Manual",
    }
]

export default carInfo;