const productInfo = [
    {
        "id": 1,
        "imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzgzddxMzIUYpbcrL_J8UMWisHVPA_dW_o7Q&usqp=CAU",
        "carName": "Nissan",
        "modelName": "Nissan",
        "bodytype": "Sedan",
        "brandName": "Limousine",
        "Budget": 53383,
        "fualtype": "Petrol",
        "transmission": "Automatic",
        "location": "Ariyalur"
    },
    {
        "id": 2,
        "imageUrl": "https://cdni.autocarindia.com/utils/imageresizer.ashx?n=https://cms.haymarketindia.net/model/uploads/modelimages/Hyundai-Verna-220320231923.jpg&w=872&h=578&q=75&c=1",
        "carName": "Van",
        "modelName": "Van",
        "bodytype": "SUV",
        "brandName": "Hyundai",
        "Budget": 55109,
        "fualtype": "Petrol",
        "transmission": "Manual",
        "location": "Chennai"
    },
    {
        "id": 3,
        "imageUrl": "https://imgd.aeplcdn.com/370x208/n/cw/ec/130591/fronx-exterior-right-front-three-quarter-109.jpeg?isig=0&q=80",
        "carName": "Jeep",
        "modelName": "Jeep",
        "bodytype": "Coupe",
        "brandName": "Minivan",
        "Budget": 36194,
        "fualtype": "Petrol",
        "transmission": "Automatic",
        "location": "Dharmapuri"
    },
    {
        "id": 4,
        "imageUrl": "https://cartoq.com/wp-content/uploads/2016/04/Convertible-XUV500-1.jpg",
        "carName": "Audi",
        "modelName": "Audi",
        "bodytype": "Coupe",
        "brandName": "Van",
        "Budget": 38723,
        "fualtype": "Petrol",
        "transmission": "Automatic",
        "location": "Erode"
    },
    {
        "id": 5,
        "imageUrl": "https://cartoq.com/wp-content/uploads/2016/04/Convertible-XUV500-1.jpg",
        "carName": "Ferrari",
        "modelName": "Ferrari",
        "bodytype": "Convertible",
        "brandName": "Hyundai",
        "Budget": 29191,
        "fualtype": "Petrol",
        "transmission": "Automatic",
        "location": "Kanchipuram"
    },
    {
        "id": 6,
        "imageUrl": "https://www.drivespark.com/img/2020/08/maruti-800-1596881162.jpg",
        "carName": "Coupe",
        "modelName": "Coupe",
        "bodytype": "SUV",
        "brandName": "Wagon",
        "Budget": 44931,
        "fualtype": "Petrol",
        "transmission": "Automatic",
        "location": "Ariyalur"
    },
    {
        "id": 7,
        "imageUrl": "https://tse1.mm.bing.net/th?id=OIP.qfYnC3S0ksRkZAvPHwdg_QHaFj&pid=Api&P=0&h=180",
        "carName": "Lamborghini",
        "modelName": "Lamborghini",
        "bodytype": "Hatchback",
        "brandName": "Renault",
        "Budget": 36719,
        "fualtype": "Petrol",
        "transmission": "Manual",
        "location": "Kanyakumari"
    },
    {
        "id": 8,
        "imageUrl": "https://www.drivespark.com/img/2020/08/maruti-800-1596881162.jpg",
        "carName": "Subaru",
        "modelName": "Subaru",
        "bodytype": "Renault",
        "brandName": "Wagon",
        "Budget": 37551,
        "fualtype": "Petrol",
        "transmission": "Automatic",
        "location": "Ariyalur"
    },
    {
        "id": 9,
        "carName": "Volvo",
        "modelName": "Volvo",
        "bodytype": "Renault",
        "brandName": "Convertible",
        "Budget": 32922,
        "fualtype": "Petrol",
        "transmission": "Manual",
        "location": "Chengalpattu"
    },
    {
        "id": 10,
        "carName": "SUV",
        "modelName": "SUV",
        "bodytype": "Minivan",
        "brandName": "Hatchback",
        "Budget": 46737,
        "fualtype": "Petrol",
        "transmission": "Automatic",
        "location": "Chengalpattu"
    },
    {
        "id": 11,
        "imageUrl": "https://tse1.mm.bing.net/th?id=OIP.qfYnC3S0ksRkZAvPHwdg_QHaFj&pid=Api&P=0&h=180",
        "carName": "Ferrari",
        "modelName": "Ferrari",
        "bodytype": "Van",
        "brandName": "Limousine",
        "Budget": 25306,
        "fualtype": "Petrol",
        "transmission": "Automatic",
        "location": "Kanchipuram"
    },
    {
        "id": 12,
        "imageUrl": "https://tse1.mm.bing.net/th?id=OIP._cHZYTClyLdE9GwzZE4mDgHaE8&pid=Api&P=0&h=180",
        "carName": "Ferrari",
        "modelName": "Ferrari",
        "bodytype": "Minivan",
        "brandName": "Convertible",
        "Budget": 35614,
        "fualtype": "Petrol",
        "transmission": "Automatic",
        "location": "Dharmapuri"
    },
    {
        "id": 13,
        "imageUrl": "https://www.drivespark.com/img/2020/08/maruti-800-1596881162.jpg",
        "carName": "Mazda",
        "modelName": "Mazda",
        "bodytype": "Wagon",
        "brandName": "Van",
        "Budget": 20365,
        "fualtype": "Petrol",
        "transmission": "Manual",
        "location": "Coimbatore"
    },
    {
        "id": 14,
        "imageUrl": "https://cdni.autocarindia.com/utils/imageresizer.ashx?n=https://cms.haymarketindia.net/model/uploads/modelimages/Hyundai-Grand-i10-Nios-200120231541.jpg&w=872&h=578&q=75&c=1",
        "carName": "Subaru",
        "modelName": "Subaru",
        "bodytype": "SUV",
        "brandName": "Wagon",
        "Budget": 34624,
        "fualtype": "Petrol",
        "transmission": "Automatic",
        "location": "Kanyakumari"
    },
    {
        "id": 15,
        "imageUrl": "https://tse1.mm.bing.net/th?id=OIP._cHZYTClyLdE9GwzZE4mDgHaE8&pid=Api&P=0&h=180",
        "carName": "Mazda",
        "modelName": "Mazda",
        "bodytype": "Limousine",
        "brandName": "Coupe",
        "Budget": 56080,
        "fualtype": "Petrol",
        "transmission": "Automatic",
        "location": "Dharmapuri"
    },
    {
        "id": 16,
        "imageUrl": "https://tse1.mm.bing.net/th?id=OIP.qfYnC3S0ksRkZAvPHwdg_QHaFj&pid=Api&P=0&h=180",
        "carName": "SUV",
        "modelName": "SUV",
        "bodytype": "Hyundai",
        "brandName": "Limousine",
        "Budget": 62254,
        "fualtype": "Petrol",
        "transmission": "Manual",
        "location": "Kanyakumari"
    },
    {
        "id": 17,
        "carName": "Hyundai",
        "modelName": "Hyundai",
        "bodytype": "Convertible",
        "brandName": "Convertible",
        "Budget": 47077,
        "fualtype": "Petrol",
        "transmission": "Automatic",
        "location": "Dindigul"
    },
    {
        "id": 18,
        "imageUrl": "https://www.drivespark.com/img/2020/08/maruti-800-1596881162.jpg",
        "carName": "Hyundai",
        "modelName": "Hyundai",
        "bodytype": "Hatchback",
        "brandName": "Minivan",
        "Budget": 36566,
        "fualtype": "Petrol",
        "transmission": "Manual",
        "location": "Dindigul"
    },
    {
        "id": 19,
        "imageUrl": "https://tse1.mm.bing.net/th?id=OIP._cHZYTClyLdE9GwzZE4mDgHaE8&pid=Api&P=0&h=180",
        "carName": "Chevrolet",
        "modelName": "Chevrolet",
        "bodytype": "Hyundai",
        "brandName": "Convertible",
        "Budget": 62531,
        "fualtype": "Petrol",
        "transmission": "Manual",
        "location": "Chengalpattu"
    },
    {
        "id": 20,
        "imageUrl": "https://tse3.mm.bing.net/th?id=OIP.CZ2otLvc6RUBbtpDJUk0tAHaFj&pid=Api&P=0&h=180",
        "carName": "Porsche",
        "modelName": "Porsche",
        "bodytype": "SUV",
        "brandName": "Wagon",
        "Budget": 52292,
        "fualtype": "Petrol",
        "transmission": "Automatic",
        "location": "Chennai"
    },
    {
        "id": 21,
        "imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzgzddxMzIUYpbcrL_J8UMWisHVPA_dW_o7Q&usqp=CAU",
        "carName": "Lexus",
        "modelName": "Lexus",
        "bodytype": "Minivan",
        "brandName": "Renault",
        "Budget": 26684,
        "fualtype": "Petrol",
        "transmission": "Automatic",
        "location": "Coimbatore"
    },
    {
        "id": 22,
        "imageUrl": "https://tse3.mm.bing.net/th?id=OIP.CZ2otLvc6RUBbtpDJUk0tAHaFj&pid=Api&P=0&h=180",
        "carName": "Wagon",
        "modelName": "Wagon",
        "bodytype": "Wagon",
        "brandName": "Convertible",
        "Budget": 31351,
        "fualtype": "Petrol",
        "transmission": "Automatic",
        "location": "Kanyakumari"
    },
    {
        "id": 23,
        "imageUrl": "https://www.drivespark.com/img/2020/08/maruti-800-1596881162.jpg",
        "carName": "Audi",
        "modelName": "Audi",
        "bodytype": "Wagon",
        "brandName": "marui suzuki",
        "Budget": 59174,
        "fualtype": "Petrol",
        "transmission": "Automatic",
        "location": "Coimbatore"
    },
    {
        "id": 24,
        "imageUrl": "https://cdni.autocarindia.com/utils/imageresizer.ashx?n=https://cms.haymarketindia.net/model/uploads/modelimages/Hyundai-Grand-i10-Nios-200120231541.jpg&w=872&h=578&q=75&c=1",
        "carName": "Jeep",
        "modelName": "Jeep",
        "bodytype": "Van",
        "brandName": "Renault",
        "Budget": 21456,
        "fualtype": "Petrol",
        "transmission": "Manual",
        "location": "Chennai"
    },
    {
        "id": 25,
        "imageUrl": "https://cartoq.com/wp-content/uploads/2016/04/Convertible-XUV500-1.jpg",
        "carName": "Kia",
        "modelName": "Kia",
        "bodytype": "Convertible",
        "brandName": "Convertible",
        "Budget": 21182,
        "fualtype": "Petrol",
        "transmission": "Manual",
        "location": "Coimbatore"
    },
    {
        "id": 26,
        "imageUrl": "https://imgd.aeplcdn.com/370x208/n/cw/ec/130591/fronx-exterior-right-front-three-quarter-109.jpeg?isig=0&q=80",
        "carName": "Chevrolet",
        "modelName": "Chevrolet",
        "bodytype": "Van",
        "brandName": "marui suzuki",
        "Budget": 51648,
        "fualtype": "Petrol",
        "transmission": "Automatic",
        "location": "Chennai"
    },
    {
        "id": 27,
        "imageUrl": "https://cdni.autocarindia.com/utils/imageresizer.ashx?n=https://cms.haymarketindia.net/model/uploads/modelimages/Hyundai-Verna-220320231923.jpg&w=872&h=578&q=75&c=1",
        "carName": "Subaru",
        "modelName": "Subaru",
        "bodytype": "Limousine",
        "brandName": "SUV",
        "Budget": 38855,
        "fualtype": "Petrol",
        "transmission": "Automatic",
        "location": "Dharmapuri"
    },
    {
        "id": 28,
        "imageUrl": "https://www.cartoq.com/wp-content/uploads/2016/08/swift.jpg",
        "carName": "Coupe",
        "modelName": "Coupe",
        "bodytype": "Minivan",
        "brandName": "Van",
        "Budget": 23227,
        "fualtype": "Petrol",
        "transmission": "Manual",
        "location": "Kanyakumari"
    },
    {
        "id": 29,
        "imageUrl": "https://cdni.autocarindia.com/utils/imageresizer.ashx?n=https://cms.haymarketindia.net/model/uploads/modelimages/Hyundai-Verna-220320231923.jpg&w=872&h=578&q=75&c=1",
        "carName": "Lamborghini",
        "modelName": "Lamborghini",
        "bodytype": "Wagon",
        "brandName": "Limousine",
        "Budget": 64941,
        "fualtype": "Petrol",
        "transmission": "Manual",
        "location": "Dindigul"
    },
    {
        "id": 30,
        "imageUrl": "https://www.cartoq.com/wp-content/uploads/2016/08/swift.jpg",
        "carName": "Lamborghini",
        "modelName": "Lamborghini",
        "bodytype": "Wagon",
        "brandName": "Hatchback",
        "Budget": 66256,
        "fualtype": "Petrol",
        "transmission": "Manual",
        "location": "Cuddalore"
    },
    {
        "id": 31,
        "carName": "Mercedes-Benz",
        "modelName": "Mercedes-Benz",
        "bodytype": "Wagon",
        "brandName": "Renault",
        "Budget": 68913,
        "fualtype": "Petrol",
        "transmission": "Manual",
        "location": "Chengalpattu"
    },
    {
        "id": 32,
        "imageUrl": "https://www.cartoq.com/wp-content/uploads/2016/08/swift.jpg",
        "carName": "SUV",
        "modelName": "SUV",
        "bodytype": "SUV",
        "brandName": "Wagon",
        "Budget": 27954,
        "fualtype": "Petrol",
        "transmission": "Automatic",
        "location": "Chennai"
    },
    {
        "id": 33,
        "imageUrl": "https://www.cartoq.com/wp-content/uploads/2016/08/swift.jpg",
        "carName": "Wagon",
        "modelName": "Wagon",
        "bodytype": "marui suzuki",
        "brandName": "Hyundai",
        "Budget": 69407,
        "fualtype": "Petrol",
        "transmission": "Manual",
        "location": "Kanyakumari"
    },
    {
        "id": 34,
        "imageUrl": "https://cartoq.com/wp-content/uploads/2016/04/Convertible-XUV500-1.jpg",
        "carName": "Ferrari",
        "modelName": "Ferrari",
        "bodytype": "SUV",
        "brandName": "Limousine",
        "Budget": 30206,
        "fualtype": "Petrol",
        "transmission": "Manual",
        "location": "Kanchipuram"
    },
    {
        "id": 35,
        "imageUrl": "https://cartoq.com/wp-content/uploads/2016/04/Convertible-XUV500-1.jpg",
        "carName": "Subaru",
        "modelName": "Subaru",
        "bodytype": "Limousine",
        "brandName": "Renault",
        "Budget": 69392,
        "fualtype": "Petrol",
        "transmission": "Manual",
        "location": "Chennai"
    },
    {
        "id": 36,
        "carName": "Van",
        "modelName": "Van",
        "bodytype": "Renault",
        "brandName": "Hatchback",
        "Budget": 32624,
        "fualtype": "Petrol",
        "transmission": "Automatic",
        "location": "Dindigul"
    },
    {
        "id": 37,
        "imageUrl": "https://cdni.autocarindia.com/utils/imageresizer.ashx?n=https://cms.haymarketindia.net/model/uploads/modelimages/Hyundai-Grand-i10-Nios-200120231541.jpg&w=872&h=578&q=75&c=1",
        "carName": "Subaru",
        "modelName": "Subaru",
        "bodytype": "Hatchback",
        "brandName": "Wagon",
        "Budget": 23691,
        "fualtype": "Petrol",
        "transmission": "Automatic",
        "location": "Kanchipuram"
    },
    {
        "id": 38,
        "carName": "Hyundai",
        "modelName": "Hyundai",
        "bodytype": "Convertible",
        "brandName": "Limousine",
        "Budget": 29639,
        "fualtype": "Petrol",
        "transmission": "Manual",
        "location": "Chengalpattu"
    },
    {
        "id": 39,
        "imageUrl": "https://cdni.autocarindia.com/utils/imageresizer.ashx?n=https://cms.haymarketindia.net/model/uploads/modelimages/Hyundai-Verna-220320231923.jpg&w=872&h=578&q=75&c=1",
        "carName": "Ferrari",
        "modelName": "Ferrari",
        "bodytype": "Wagon",
        "brandName": "Wagon",
        "Budget": 69419,
        "fualtype": "Petrol",
        "transmission": "Manual",
        "location": "Kanchipuram"
    },
    {
        "id": 40,
        "imageUrl": "https://tse3.mm.bing.net/th?id=OIP.CZ2otLvc6RUBbtpDJUk0tAHaFj&pid=Api&P=0&h=180",
        "carName": "Ferrari",
        "modelName": "Ferrari",
        "bodytype": "marui suzuki",
        "brandName": "Renault",
        "Budget": 28614,
        "fualtype": "Petrol",
        "transmission": "Manual",
        "location": "Dharmapuri"
    },
    {
        "id": 41,
        "imageUrl": "https://tse3.mm.bing.net/th?id=OIP.CZ2otLvc6RUBbtpDJUk0tAHaFj&pid=Api&P=0&h=180",
        "carName": "Van",
        "modelName": "Van",
        "bodytype": "Convertible",
        "brandName": "Minivan",
        "Budget": 30379,
        "fualtype": "Petrol",
        "transmission": "Automatic",
        "location": "Dharmapuri"
    },
    {
        "id": 42,
        "imageUrl": "https://www.drivespark.com/img/2020/08/maruti-800-1596881162.jpg",
        "carName": "Volvo",
        "modelName": "Volvo",
        "bodytype": "Convertible",
        "brandName": "SUV",
        "Budget": 41416,
        "fualtype": "Petrol",
        "transmission": "Automatic",
        "location": "Kanyakumari"
    },
    {
        "id": 43,
        "imageUrl": "https://tse1.mm.bing.net/th?id=OIP.qfYnC3S0ksRkZAvPHwdg_QHaFj&pid=Api&P=0&h=180",
        "carName": "Kia",
        "modelName": "Kia",
        "bodytype": "Renault",
        "brandName": "marui suzuki",
        "Budget": 51077,
        "fualtype": "Petrol",
        "transmission": "Automatic",
        "location": "Chennai"
    },
    {
        "id": 44,
        "imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzgzddxMzIUYpbcrL_J8UMWisHVPA_dW_o7Q&usqp=CAU",
        "carName": "Mazda",
        "modelName": "Mazda",
        "bodytype": "Renault",
        "brandName": "Hyundai",
        "Budget": 32442,
        "fualtype": "Petrol",
        "transmission": "Manual",
        "location": "Coimbatore"
    },
    {
        "id": 45,
        "imageUrl": "https://cdni.autocarindia.com/utils/imageresizer.ashx?n=https://cms.haymarketindia.net/model/uploads/modelimages/Hyundai-Grand-i10-Nios-200120231541.jpg&w=872&h=578&q=75&c=1",
        "carName": "Volvo",
        "modelName": "Volvo",
        "bodytype": "Renault",
        "brandName": "Limousine",
        "Budget": 25980,
        "fualtype": "Petrol",
        "transmission": "Automatic",
        "location": "Kanchipuram"
    },
    {
        "id": 46,
        "imageUrl": "https://www.drivespark.com/img/2020/08/maruti-800-1596881162.jpg",
        "carName": "Volvo",
        "modelName": "Volvo",
        "bodytype": "Convertible",
        "brandName": "Renault",
        "Budget": 52385,
        "fualtype": "Petrol",
        "transmission": "Automatic",
        "location": "Erode"
    },
    {
        "id": 47,
        "imageUrl": "https://cdni.autocarindia.com/utils/imageresizer.ashx?n=https://cms.haymarketindia.net/model/uploads/modelimages/Hyundai-Grand-i10-Nios-200120231541.jpg&w=872&h=578&q=75&c=1",
        "carName": "Porsche",
        "modelName": "Porsche",
        "bodytype": "Renault",
        "brandName": "Minivan",
        "Budget": 55968,
        "fualtype": "Petrol",
        "transmission": "Manual",
        "location": "Chennai"
    },
    {
        "id": 48,
        "imageUrl": "https://tse1.mm.bing.net/th?id=OIP._cHZYTClyLdE9GwzZE4mDgHaE8&pid=Api&P=0&h=180",
        "carName": "Porsche",
        "modelName": "Porsche",
        "bodytype": "Coupe",
        "brandName": "marui suzuki",
        "Budget": 43277,
        "fualtype": "Petrol",
        "transmission": "Manual",
        "location": "Kallakurichi"
    },
    {
        "id": 49,
        "imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzgzddxMzIUYpbcrL_J8UMWisHVPA_dW_o7Q&usqp=CAU",
        "carName": "Coupe",
        "modelName": "Coupe",
        "bodytype": "Minivan",
        "brandName": "Van",
        "Budget": 44420,
        "fualtype": "Petrol",
        "transmission": "Automatic",
        "location": "Erode"
    },
    {
        "id": 50,
        "imageUrl": "https://www.cartoq.com/wp-content/uploads/2016/08/swift.jpg",
        "carName": "Lexus",
        "modelName": "Lexus",
        "bodytype": "Hatchback",
        "brandName": "marui suzuki",
        "Budget": 54399,
        "fualtype": "Petrol",
        "transmission": "Automatic",
        "location": "Erode"
    }
]

export default productInfo;